# Generated by Django 3.0.4 on 2020-03-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('flybox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='automataflyboxa', serialize=False, to='home.Flyboxset')),
                ('mondaycd', models.BooleanField(default=False)),
                ('tuesdaycd', models.BooleanField(default=False)),
                ('wednesdaycd', models.BooleanField(default=False)),
                ('thursdaycd', models.BooleanField(default=False)),
                ('fridaycd', models.BooleanField(default=False)),
                ('saturdaycd', models.BooleanField(default=False)),
                ('sundaycd', models.BooleanField(default=False)),
                ('mondaypd', models.BooleanField(default=False)),
                ('tuesdaypd', models.BooleanField(default=False)),
                ('wednesdaypd', models.BooleanField(default=False)),
                ('thursdaypd', models.BooleanField(default=False)),
                ('fridaypd', models.BooleanField(default=False)),
                ('saturdaypd', models.BooleanField(default=False)),
                ('sundaypd', models.BooleanField(default=False)),
            ],
        ),
    ]
