# Generated by Django 3.0.4 on 2020-03-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_automation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='fridaycd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='fridaypd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='mondaycd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='mondaypd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='saturdaycd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='saturdaypd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='sundaycd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='sundaypd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='thursdaycd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='thursdaypd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='tuesdaycd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='tuesdaypd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='wednesdaycd',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='wednesdaypd',
        ),
        migrations.AddField(
            model_name='automation',
            name='cddays',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='cdtime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='pddays',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='pddtime',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
