# Generated by Django 3.0.4 on 2020-03-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200310_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='setupcompleted',
            field=models.BooleanField(default=False),
        ),
    ]
