# Generated by Django 3.0.4 on 2020-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_automation_setupcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='cdenabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automation',
            name='pdenabled',
            field=models.BooleanField(default=False),
        ),
    ]
