# Generated by Django 3.0.4 on 2020-03-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200311_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automationpd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pddtime', models.CharField(max_length=200, null=True)),
                ('pddays', models.CharField(max_length=200, null=True)),
                ('setupcompleted', models.BooleanField(default=False)),
                ('pdenabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='automation',
            name='pddays',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='pddtime',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='pdenabled',
        ),
    ]
