# Generated by Django 3.0.4 on 2020-03-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200311_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationpd',
            name='id',
        ),
        migrations.AddField(
            model_name='automationpd',
            name='flybox',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='automatapdflyboxa', serialize=False, to='home.Flyboxset'),
            preserve_default=False,
        ),
    ]
